name: time_logger_app
description: "ØªØ§ÛŒÙ… Ù„Ø§Ú¯Ø± Ø­Ø±ÙÙ‡â€ŒØ§ÛŒ â€” Ø³Ø§Ø²Ù†Ø¯Ù‡: Ú©ÙˆØ±Ø´ Ø´ÛŒØ±Ø§Ø²"
publish_to: 'none'
version: 3.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.2
  path_provider: ^2.1.4
  intl: ^0.19.0
  fl_chart: ^0.69.0
  table_calendar: ^3.1.2
  file_picker: ^8.1.2
  audioplayers: ^6.1.0
  permission_handler: ^11.3.1
  android_alarm_manager_plus: ^4.0.6
  flutter_ringtone_player: ^4.0.0
  excel: ^4.0.3
  pdf: ^3.11.1
  flutter_pdfview: ^1.3.2
  printing: ^5.13.2
  share_plus: ^10.0.2
  screenshot: ^3.0.0
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  device_calendar: ^4.3.2
  add_2_calendar: ^3.0.1
  local_auth: ^2.3.0
  pin_code_fields: ^8.0.1
  url_launcher: ^6.3.0
  webview_flutter: ^4.10.0
  google_mobile_ads: ^5.2.0
  uuid: ^4.5.1
  package_info_plus: ^8.1.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon_512.png"
  adaptive_icon_background: "#0B1E3F"
  adaptive_icon_foreground: "assets/icon/icon_512.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/icon/