name: time_logger_app
description: "ØªØ§ÛŒÙ… Ù„Ø§Ú¯Ø± â€” Ø³Ø§Ø²Ù†Ø¯Ù‡: Ú©ÙˆØ±Ø´ Ø´ÛŒØ±Ø§Ø²"
publish_to: 'none'
version: 1.4.0+5

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  url_launcher: ^6.3.0
  fl_chart: ^0.69.0
  file_picker: ^8.1.2
  path_provider: ^2.1.4
  share_plus: ^10.0.2
  device_calendar: ^4.3.2
  syncfusion_flutter_pdfviewer: ^27.1.48
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  audioplayers: ^6.1.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon_512.png"
  adaptive_icon_background: "#1C1C20"
  adaptive_icon_foreground: "assets/icon/icon_512.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/publications/